spring:
  application:
    name: genericshop
  datasource:
    url: jdbc:mysql://localhost:3306/genericshop
    username: root
    password: qwer
  jpa:
    show-sql: true


logging:
  level:
    com.stepit.lecture.genericshop: debug

  pattern:
    console: "%d{YYYY-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} | %msg%n"
    file: "%d{YYYY-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} | %msg%n"

  file:
    name: genericshop.log
    append: false


server:
  port: 8085

eureka:
  client:
    enabled: true

app:
  api:
    path:
      version:
        v1: "/api/v1"
      building:
        createBuilding: "/building/create"
        getBuilding: "/building"
        getBuildings: "/buildings"
        deleteBuilding: "/building/delete"
        updateBuilding: "/building/update"
      address:
        createAddress: "/address/create"
        getAddress: "/address"
        getAddresses: "/addresses"
        updateAddress: "/address/update"
        deleteAddress: "/address/delete"
      user:
        getUser: "/user"


