spring:
  application:
    name: genericshop
  datasource:
    url: jdbc:mysql://localhost:3306/genericshop
    username: root
    password: qwer
  jpa:
    show-sql: true


logging:
  level:
    com.stepit.lecture.genericshop: error
    org.springframework.web: debug

  pattern:
    console: "%d{MM-dd HH:mm:ss} [%thread] %-5level %logger{36} | %msg%n"
    file: "%d{YYYY-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} | %msg%n"

  file:
    name: genericshop.log
    append: false
    max-size: 10MB
    max-history: 5


server:
  port: 8085

app:
  api:
    path:
      version:
        v1: "/api/v1"
      building:
        createBuilding: "/building/create"
        getBuilding: "/building"
        deleteBuilding: "/building/delete"
        updateBuilding: "/building/update"
      address:
        createAddress: "/address/create"


